distributable:
  url: https://github.com/mac-cain13/R.swift/releases/download/{{version}}/rswift-{{version}}.zip

versions:
  github: mac-cain13/R.swift

platforms:
  - darwin

provides:
  - bin/rswift

warnings:
  - vendored

build:
  working-directory: vendor
  script: |
    curl -Lfo rswift.zip "https://github.com/mac-cain13/R.swift/releases/download/{{version}}/rswift-{{version}}.zip"
    unzip rswift.zip
    mkdir -p "{{prefix}}/bin"
    mv rswift/rswift "{{prefix}}/bin"

test:
  script: |
    [[ "$(rswift --version)" = "{{version}}" ]]
