distributable:
  url: https://github.com/rubygems/gemx/archive/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: rubygems/gemx/tags

dependencies:
  ruby-lang.org: ^3.1
  rubygems.org: '*'

build:
  env:
    GEM_HOME: ${{prefix}}
    GEM_PATH: ${{prefix}}
  dependencies:
    rubygems.org: '*'
    git-scm.org: '*'
  script: |
    gem install bundler
    sed -i.bak -e "s/spec.add_development_dependency 'bundler',.*/spec.add_development_dependency 'bundler', '~> 2.4'/" \
               -e "s/spec.add_development_dependency 'rubocop',.*/spec.add_development_dependency 'rubocop', '~> 0.49.0'/" \
               -e "s/spec.add_development_dependency 'rake',.*/spec.add_development_dependency 'rake', '~> 10.2.0'\nspec.add_development_dependency 'rainbow', '~> 2.1.0'/" \
               gemx.gemspec

    ./bin/setup
    # gem build gemx.gemspec

    gem install \
      --no-user-install \
      --bindir={{prefix}}/gems/bin \
      --no-document \
      gemx.gemspec
      # gemx-{{version}}.gem

    mv props/gemx "{{prefix}}"/bin

provides:
  - bin/gemx

test: gemx ruby-macho