distributable:
  url: https://ftp.gnu.org/gnu/glibc/glibc-{{ version.raw }}.tar.gz
  strip-components: 1

versions:
  #TODO HTML listing: https://ftp.gnu.org/gnu/glibc/
  # - 2.28
  - 2.33

platforms: linux

build:
  dependencies:
    gnu.org/make: '>=3.79'
    gnu.org/gawk: '>=3'
    gnu.org/gcc: '*'
    gnu.org/gettext: '*'
    gnu.org/texinfo: '*'
    gnu.org/bison: '*'
    gnu.org/sed: '*'
    perl.org: '*'
    python.org: ^3
    kernel.org/linux-headers: '~5.15'
  working-directory: build
  script: |
    ../configure $ARGS
    make all #-j {{hw.concurrency}}
    make test
    make install

    cd {{prefix}}/bin
    for s in $SCRIPTS; do
      sed -i.bak 's|{{prefix}}|"$(cd "$(dirname "$0")/.." \&\& pwd)"|' $s
      rm $s.bak
    done

    ln -s ../lib/ld-{{ version.marketing }}.so ld.so
  test:
    make test
  env:
    SCRIPTS:
      - catchsegv
      - ldd
      - mtrace
      - sotruss
      - tzselect
      - xtrace
    ARGS:
      - --prefix={{ prefix }}
      - --disable-crypt
      - --disable-debug
      - --disable-dependency-tracking
      - --disable-silent-rules
      - --disable-werror
      - --enable-obsolete-rpc
      - --without-gd
      - --without-selinux
      - --with-binutils={{deps.gnu.org/binutils.prefix}}/bin
      - --with-headers={{deps.kernel.org/linux-headers.prefix}}/include
      # ChatGPT
      - --disable-multi-arch
    CFLAGS: -O2
    linux/x86-64:
      CFLAGS: -O2 -fPIC
      CXXFLAGS: -O2 -fPIC
      LDFLAGS: -pie

test:
  dependencies:
    gnu.org/gcc: '*'
  script: |
    {{prefix}}/lib/ld-{{ version.marketing }}.so --version
    ld.so --version

    # Putting ourselves in the LD_LIBRARY_PATH breaks literally everything else...
    export LD_LIBRARY_PATH=$(echo LD_LIBRARY_PATH | tr ':' '\n' | grep -v {{prefix}} | tr '\n' ':')
    case "{{hw.arch}}" in
      x86-64) ARCH=x86_64;;
      aarch64) ARCH=aarch64;;
      *)
        echo "Unsupported architecture {{hw.arch}}"
        exit 1
        ;;
    esac
    gcc \
      -nostdinc \
      -nostdlib \
      -L{{prefix}}/lib \
      -I{{prefix}}/include \
      -I{{deps.gnu.org/gcc.prefix}}/lib/gcc/$ARCH-unknown-linux-gnu/{{deps.gnu.org/gcc.version}}/include \
      -Wl,--rpath="{{prefix}}/lib" \
      -Wl,--dynamic-linker={{prefix}}/lib/ld-{{ version.marketing }}.so \
      -std=c11 \
      -o test \
      -v \
      $CFLAGS \
      {{prefix}}/lib/crti.o \
      {{prefix}}/lib/crtn.o \
      test.c \
      -pthread \
      -static \
      -fPIC \
      -pie
    objdump -p test
    ./test

provides:
  - bin/catchsegv
  - bin/gencat
  - bin/getconf
  - bin/getent
  - bin/iconv
  - bin/ld.so
  - bin/ldd
  - bin/locale
  - bin/localedef
  - bin/makedb
  - bin/mtrace
  - bin/pcprofiledump
  - bin/pldd
  - bin/sotruss
  - bin/sprof
  - bin/tzselect
  - bin/xtrace
  - sbin/iconvconfig
  - sbin/ldconfig
  - sbin/nscd
  - sbin/sln
  - sbin/zdump
  - sbin/zic
